/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sv.edu.udb.biblioteca;
import Conexion.Conexion;
import java.sql.SQLException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Will
 */
public class Devolucion_material extends javax.swing.JInternalFrame {

ResultSet llenartabla;
    public Devolucion_material() throws SQLException{

        initComponents();
        datosdevolucion();
          }
    
    void datosdevolucion()
    {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID prestamo");
        modelo.addColumn("Carnet");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Cargo");
        modelo.addColumn("Codigo del material");
        modelo.addColumn("Nombre del material");
        modelo.addColumn("Estante");
      
        tbDevolucion.setModel(modelo);
        String []datos = new String [8];
        try {
            Conexion mostrar = new Conexion();
            //Statement st = cn.createStatement();
            //ResultSet rs = st.executeQuery
        mostrar.setRs("select pm.id_prestamo_material, carnet_personal, nombre_personal, apellido_personal, tp.nombre_personal_tipo, codigo_material, nombre_material, e.estante\n" +
"from personal p\n" +
"inner join prestamo_material pm\n" +
"on p.carnet_personal=pm.carnet_personal_p_m\n" +
"inner join material m\n" +
"on pm.codigo_material_p_m=m.codigo_material\n" +
"inner join ejemplar e\n" +
"on m.codigo_material=e.id_ejemplar\n" +
"inner join tipo_personal tp\n" +
"on tp.id_tipo_personal=p.id_tipo_personal\n" +
"where e.id_estado_ejemplar = 'EE1'");
        llenartabla=(ResultSet) mostrar.getRs();
            while(llenartabla.next()){
              datos[0]=llenartabla.getString(1);
              datos[1]=llenartabla.getString(2);
              datos[2]=llenartabla.getString(3);
              datos[3]=llenartabla.getString(4);
              datos[4]=llenartabla.getString(5);
              datos[5]=llenartabla.getString(6);
              datos[6]=llenartabla.getString(7);
              datos[7]=llenartabla.getString(8);
                                                                                         
              modelo.addRow(datos);
            }
            tbDevolucion.setModel(modelo);
            mostrar.cerrarConexion();
                    } catch (SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDevolucion = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtnid = new javax.swing.JTextField();
        txtmaterial = new javax.swing.JTextField();
        txtcarnet = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        devolver = new javax.swing.JButton();
        regresar = new javax.swing.JButton();

        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        tbDevolucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDevolucion.setComponentPopupMenu(jPopupMenu1);
        tbDevolucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDevolucionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbDevolucion);

        jLabel22.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel22.setText("Devolución de material");

        jLabel23.setText("Carnet:");

        jLabel24.setText("ID prestamo");

        jLabel26.setText("Codigo de material:");

        txtnid.setEditable(false);

        txtmaterial.setEditable(false);

        txtcarnet.setEditable(false);

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        devolver.setText("Devolución");
        devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverActionPerformed(evt);
            }
        });

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtnid, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addComponent(jLabel26)
                        .addGap(51, 51, 51)
                        .addComponent(txtmaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(regresar, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(devolver))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(txtmaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtcarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txtnid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(devolver, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void llenarjtable() throws SQLException
    {
        Conexion con = new Conexion();
        con.cerrarConexion();
        
    }
    
    public void abrirbase() throws SQLException, ClassNotFoundException
    {
 
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void devolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverActionPerformed
      
        try
        {  
            //PreparedStatement pst = cn.prepareStatement
            Conexion actualizar =new Conexion();
                   actualizar.setQuery("update ejemplar e, prestamo_material pm set pm.id_estado_prestamo = 'EP3', e.id_estado_ejemplar='EE4' where pm.id_prestamo_material="+txtnid.getText()+"&& e.id_ejemplar='"+txtmaterial.getText()+"'");
           // pst.executeUpdate();
            
            limpiar();
            datosdevolucion();
        }
        catch(SQLException e)
        {
            System.out.println(e.getMessage());
        }
    
    }//GEN-LAST:event_devolverActionPerformed

    public void limpiar()
    {   
        txtnid.setText(null);
        txtcarnet.setText(null);
        txtmaterial.setText(null);
        datosdevolucion();
    }
    private void tbDevolucionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDevolucionMouseClicked
        // TODO add your handling code here:
        int fila = tbDevolucion.getSelectedRow();
        if(fila>=0)
        {
        txtnid.setText(tbDevolucion.getValueAt(fila,0).toString());     
        txtcarnet.setText(tbDevolucion.getValueAt(fila,1).toString());
        txtmaterial.setText(tbDevolucion.getValueAt(fila,5).toString());
        
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Fila no seleccionada");
        }
        
    }//GEN-LAST:event_tbDevolucionMouseClicked

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
       this.setVisible(false);
            Bibliotecario Biblio = new Bibliotecario();
            MDIprincipal.Escritorio.add(Biblio);
            Biblio.toFront();
            Biblio.setVisible(true);
    }//GEN-LAST:event_regresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton devolver;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton regresar;
    private javax.swing.JTable tbDevolucion;
    private javax.swing.JTextField txtcarnet;
    private javax.swing.JTextField txtmaterial;
    private javax.swing.JTextField txtnid;
    // End of variables declaration//GEN-END:variables
        /*Conexion cc = new Conexion();
        Connection cn = cc.Conexion();*/
}


