/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sv.edu.udb.biblioteca;

import Conexion.Conexion;
import java.sql.*;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.Random;
import java.util.function.Supplier;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sv.edu.udb.biblioteca.Registro_from_Admin;

/**
 *
 * @author Will
 */
public class Registro_material_audiovisual extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registro_material_audiovisual
     */
    public Registro_material_audiovisual() {
        initComponents();
    }
    
    public static void main(String[] args){
        Registro_material_audiovisual r = new Registro_material_audiovisual();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_material_audiovisual().setVisible(true);
            }
        });
    }
    
    public String ValidarDatos() {//Metodo para comprobar que los datos esten completos
        String msj = "";
        if (jTextField8.getText().equals("")) {//Si txtID esta vacio
            msj += "Por favor digite el codigo de la materia. \n";
        }
        if (jTextField5.getText().equals("")) {//Si txtNombre esta vacio
            msj += "Por favor digite el nombre del material. \n";
        }
        if (textField1.getText().equals("")) {//Si txtNombre esta vacio
            msj += "Por favor digite el resumen. \n";
        }
        if (jTextField7.getText().equals("")) {//Si txtNombre esta vacio
            msj += "Por favor digite la fecha de publicacion. \n";
        }
        if (jTextField9.getText().equals("")) {//Si txtNombre esta vacio
            msj += "Por favor digite la fecha de adquisicion. \n";
        }
        if (jTextField10.getText().equals("")) {//Si txtNombre esta vacio
            msj += "Por favor digite la cantidad del material. \n";
        }
        if (jTextField13.getText().equals("")) {//Si txtNombre esta vacio
            msj += "Por favor digite la duracion del material. \n";
        }
        if (jTextField14.getText().equals("")) {//Si txtNombre esta vacio
            msj += "Por favor digite la descripcion. \n";
        }
        return msj;//devuelve msj
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel27 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        textField1 = new java.awt.TextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();

        jLabel27.setText("Fecha de adquisicion:");

        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField13KeyTyped(evt);
            }
        });

        textField1.setText("textField1");
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        textField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField1KeyTyped(evt);
            }
        });

        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField10KeyTyped(evt);
            }
        });

        jLabel28.setText("Cantidad de material: ");

        jLabel23.setText("Codigo materia:");

        jLabel32.setText("Duracion:");

        jLabel33.setText("Descripcion:");

        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField14KeyTyped(evt);
            }
        });

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jLabel25.setText("Resumen:");

        jLabel26.setText("Fecha de publicacion:");

        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sv/edu/udb/biblioteca/img/Guardar.jpg"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel22.setText("Material audiovisual");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sv/edu/udb/biblioteca/img/regresar.jpg"))); // NOI18N
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9KeyTyped(evt);
            }
        });

        jLabel24.setText("Nombre del material:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(textField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel27)
                                .addComponent(jLabel26)
                                .addComponent(jLabel28))
                            .addComponent(jLabel33)
                            .addComponent(jLabel32)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(67, 67, 67)
                .addComponent(jButton2)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Random cod = new Random();
//        if (jTextField8.getText().isEmpty())  {
//            JOptionPane.showMessageDialog(null, "Ingrese el Codigo del Material","error",JOptionPane.ERROR_MESSAGE);
//        }
        if (jTextField5.getText().isEmpty())  {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre del material","error",JOptionPane.ERROR_MESSAGE);
        }
        if (textField1.getText().isEmpty())  {
            JOptionPane.showMessageDialog(null, "Ingrese un Resumen","error",JOptionPane.ERROR_MESSAGE);
        }
        if (jTextField7.getText().isEmpty())  {
            JOptionPane.showMessageDialog(null, "Ingrese la fecha de publicacion","error",JOptionPane.ERROR_MESSAGE);
        }
        if (jTextField9.getText().isEmpty())  {
            JOptionPane.showMessageDialog(null, "Ingrese la fecha de adquisicion","error",JOptionPane.ERROR_MESSAGE);
        }
        if (jTextField10.getText().isEmpty())  {
            JOptionPane.showMessageDialog(null, "Ingrese la cantidad del material","error",JOptionPane.ERROR_MESSAGE);
        }
        if (jTextField13.getText().isEmpty())  {
            JOptionPane.showMessageDialog(null, "Ingrese la Duracion del material","error",JOptionPane.ERROR_MESSAGE);
        }
        if (jTextField14.getText().isEmpty())  {
            JOptionPane.showMessageDialog(null, "Ingrese una descripcion","error",JOptionPane.ERROR_MESSAGE);
        }
        try {
            // TODO add your handling code here:

            
            String idmaterialaudi = "AV" + cod.nextInt(99);
            int duracion=Integer.parseInt(jTextField13.getText());
            String codmaterial= jTextField8.getText();//"M" + numero;
            String descrip=jTextField14.getText();
            String coddmaterial = codmaterial;
            String nombrematerial=jTextField5.getText();
            String idcodmaterial = "22";
            String resumen=textField1.getText();
            String fpublic=jTextField7.getText();
            String fadquis=jTextField9.getText();
            int cantidad=Integer.parseInt(jTextField10.getText());
            guardarDatos(idmaterialaudi, duracion, coddmaterial, descrip, codmaterial, nombrematerial, idcodmaterial, resumen, fpublic, fadquis, cantidad);
            
            //guardarDatos2(codmaterial, nombrematerial, resumen, fpublic, fadquis, cantidad);
            
        } catch (SQLException ex) {
            Logger.getLogger(Registro_material_audiovisual.class.getName()).log(Level.SEVERE, null, ex);
        }
        limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void guardarDatos(String idmaterialaudi, int duracion, String coddmaterial, String descrip, String codmaterial, String nombrematerial, String idcodmaterial, String resumen, String fpublic, String fadquis, int cantidad) throws SQLException{
    try{
    Conexion guardar=new Conexion();
        //guardar.setQuery("insert into material_audiovisual values('"+idmaterialaudi+"','"+duracion+"','"+idtipomaterial+"','"+descrip+"')");
        guardar.setQuery("insert into material values('"+codmaterial+"','"+nombrematerial+"','"+idcodmaterial+"','"+resumen+"','"+fpublic+"','"+fadquis+"','"+cantidad+"')");
        guardar.setQuery2("insert into material_audiovisual values('"+idmaterialaudi+"','"+duracion+"','"+coddmaterial+"','"+descrip+"')");
        
        
        //guardar.setQuery("select m.* from material m inner join material_escrito me on m.codigo_material=me.codigo_material where m.codigo_material=me.codigo_material");
        //guardar.setQuery("select * ");
        
        JOptionPane.showMessageDialog(null, "Registro Ingresado Exitosamente");
        guardar.cerrarConexion();
            } catch (SQLException ex) {
                Logger.getLogger(Registro_material_audiovisual.class.getName()).log(Level.SEVERE, null, ex);
            }
}
    
//    public void guardarDatos2(String codmaterial, String nombrematerial, String resumen, String fpublic, String fadquis, int cantidad) throws SQLException{
//    try{
//    prueba.Conexion guardar=new prueba.Conexion();
//        guardar.setQuery("insert into material values('"+codmaterial+"','"+nombrematerial+"','"+resumen+"','"+fpublic+"','"+fadquis+"','"+cantidad+"')");
//        JOptionPane.showMessageDialog(null, "Registro Ingresado Exitosamente");
//        guardar.cerrarConexion();
//            } catch (SQLException ex) {
//                Logger.getLogger(Registro_material_audiovisual.class.getName()).log(Level.SEVERE, null, ex);
//            }
//}
    
    private void limpiar(){
        jTextField8.setText("");
        jTextField5.setText("");
        textField1.setText("");
        jTextField7.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Consulta consulta = null;
        consulta = new Consulta();
        consulta.setVisible(true);
        this.setVisible(false);//oculta el jFrame que estes usando
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
     
if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_jTextField8KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
     
if((c<'a' || c>'z') && (c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_jTextField5KeyTyped

    private void textField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
     
if((c<'a' || c>'z') && (c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_textField1KeyTyped

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        // TODO add your handling code here:
        isFechaValida(jTextField7.getText());
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped
        // TODO add your handling code here:
        isFechaValida(jTextField9.getText());
    }//GEN-LAST:event_jTextField9KeyTyped

    private void jTextField10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
     
if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_jTextField10KeyTyped

    private void jTextField13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13KeyTyped

    private void jTextField14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
     
if((c<'a' || c>'z') && (c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_jTextField14KeyTyped

    public static boolean isFechaValida(String fecha) {
        try {
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy", Locale.getDefault());
            formatoFecha.setLenient(false);
            formatoFecha.parse(fecha);
        } catch (ParseException e) {
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}


// Definimos el driver y la url
//String sDriver = "com.mysql.jdbc.Driver";
//String sURL = "jdbc:mysql://localhost:3306/lineadecodigo";
//Connection con = null;
//Class.forName(sDriver).newInstance(); 
//con = DriverManager.getConnection(sURL,"root","root");
//PreparedStatement stmt = con.prepareStatement("INSERT INTO material_audiovisual VALUES (?,?,?,?)");
//String sIMAV = jTextField8.getText();
//int sduracion = Integer.parseInt(textField1.getText());
//String scodmateria= jTextField5.getText();
//String sDesc = jTextField13.getText();
//
//stmt.setString(1,null);
//stmt.setString(2,sIMAV);
//stmt.setInt(3,sduracion);
//stmt.setString(4,scodmateria);
//stmt.setString(5,sDesc);
//
//stmt.executeUpdate();
/////////////////////////////////////////////////////////////////////
//        try {
//            // TODO add your handling code here:
//            
//            Statement s = (Statement) con.createStatement();
//            String idmaterial = "AV" + cod.nextInt(99);
//            String codmaterial=jTextField8.getText();
//            String duracion=jTextField13.getText();
//            String descrip=jTextField14.getText();
//            s.execute("insert into material_audiovisual values('"+idmaterial+"','"+duracion+"','"+descrip+"')");
////            con.setQuery("insert into material_audiovisual values("+idmaterial+"\","+textField1.getText()+"\","
////                    +jTextField13.getText()+"\","+jTextField8.getText()+"\","+jTextField14.getText()+"\")");
//            String nombrematerial=jTextField5.getText();
//            String resumen=textField1.getText();
//            String fpublic=jTextField7.getText();
//            String fadquis=jTextField9.getText();
//            String cantidad=jTextField10.getText();
//            s.execute("insert into material values('"+codmaterial+"','"+nombrematerial+"','"+resumen+"','"+fpublic+"','"+fadquis+"','"+cantidad+"')");
////            con.setQuery("insert into material values("+jTextField10.getText()+jTextField7.getText()+"\","
////                    +jTextField9.getText()+"\")");
//            
//            
//////// VALIDACION SI EXISTEN CAMPOS VACIOS/////////////
//        if (ValidarDatos().equals("")) {//Si el medoto ValidarDatos devuelve "", es decir, nada es porque
//            //los dos campos estan llenos
////            JOptionPane.showMessageDialog(rootPane, "Los dos datos han sido ingresados :-)", "Validando Datos",
////                    JOptionPane.INFORMATION_MESSAGE);
//        } else {//de lo contrario emite el mensaje
//            JOptionPane.showMessageDialog(rootPane, "ERROR!! \n" + ValidarDatos(), "Validando Datos",
//                    JOptionPane.ERROR_MESSAGE);
//        }
//            JOptionPane.showMessageDialog(this, "Material Ingresado Exitosamente");
//            s.close();
//            con.close();
//            limpiar();
//            //statement.execute("insert into material values('"+codigo_material+"','"+nombre_material+"','"
//            //+id_tipo_material+"','"+resumen+"','"+fecha_publicacion+"','"+fecha_adquisicion+"','"+cantidad_material+"')");
//        } catch (SQLException ex) {
//            Logger.getLogger(Registro_material_escrito.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog(this, "Error "+ex.getMessage());
//        }